/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code;

import java.io.File;
import java.net.URISyntaxException;

public class App {

    public static void main(String[] args) throws URISyntaxException {
        File test = new File(ClassLoader.getSystemResource("201501_input").toURI());
        System.out.println(test.exists());
    }
}
