/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URISyntaxException;

import year2024.Day01HistorianHysteria;

public class App {

    public static void main(String[] args) throws URISyntaxException, IOException {
        FileReader input = new FileReader(ClassLoader.getSystemResource("202401_input").getPath());

        Integer result = Day01HistorianHysteria.part2(input);
        
        System.out.println(String.format("The result is %d", result));
        
        input.close();
    }
}
